version: "3.8"
services:
  python-web3-etl-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-web3-etl-backend
    ports:
      - 8080:8080
    volumes:
      - .:/python-web3-etl-backend

volumes:
  data: {}

networks:
  default:
    name: mongodb_network