version: "3.8"
services:
  python-web3-etl-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-web3-etl-backend
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/python-web3-etl-backend
    command: python3 run_api.py
  
  # Enable this to use mongodb and mongo-express in the same
  # Docker container.
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - data:/data
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=pass
  
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
  #     - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network